export const PRODUCT_CATEGORIES = 'PRODUCT_CATEGORIES';
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const IS_LOGIN = 'IS_LOGIN';
export const ADD_WORKER = "ADD_WORKER";
export const GET_PRODUCT= "GET_PRODUCT";